### ISSUE TITLE
Can't set homepage as localhost

### ISSUE THREAD

**Issue by iBreakEverything** [plaskowski/EmbeddedBrowserIntellijPlugin#16]
Or any other page that can't be loaded (ERR_NAME_NOT_RESOLVED or ERR_CONNECTION_REFUSED)
Sure, you could "fix" this by adding a home button and saving the url in the address bar regardless of the response.

This plugin is very usefull for quick debugging for me. Thank you

**Comment by plaskowski** [comment]
Hi,
thank you for the report. I am happy you have found the plugin useful.

Can I ask you to provide more details:
- what Intellij version do you use?
- did you mean ".initial_url" plugin property by saying "homepage"?
- what exactly happens:
  - can you navigate to different URL (by entering it into address bar and pressing Enter)?
  - can you navigate to localhost after it becomes a reachable address?
  - can you refresh the error page after the localhost becomes a reachable address?

Bests,
Piotr

**Comment by iBreakEverything** [comment]
- what Intellij version do you use?
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021

- did you mean ".initial_url" plugin property by saying "homepage"?
yes, i set it like this
<property name="com.github.plaskowski.embeddedbrowserintellijplugin.initial_url" value="localhost:8080" />

- what exactly happens:
  - can you navigate to different URL (by entering it into address bar and pressing Enter)?
  yes
  - can you navigate to localhost after it becomes a reachable address?
  yes
  - can you refresh the error page after the localhost becomes a reachable address?
  yes (solved, thank you)

so, in case of an error the address bar will remain empty and i do not get an error page, just a blank page

**Comment by plaskowski** [comment]
Hi @iBreakEverything,
do I assume correctly that:
- refreshing by entering the address is good enough workaround?
- to fully support your use case you would expect to see an error page and be able to reload it (with reload button) after it becomes reachable?

Bests,
Piotr

**Comment by iBreakEverything** [comment]
if the url becomes a reachable address then the refresh button will work
but
some feedback (an error page) from the plugin would be welcome
