### ISSUE TITLE
[question] qustion in using JCEF

### ISSUE THREAD

**Issue by sangho-jeon** [plaskowski/EmbeddedBrowserIntellijPlugin#49]
hi, im currently testing this plugin and want to customize it. i'm using mac and faced with JCEF issue. 
with a error message "java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize", how did you solved this problem? if the problem did not occurred in your case, can you tell me what jdk version did you used?

**Comment by plaskowski** [comment]
Hi,
I am on vacation till July 24th. I will take a look afterwards.
Cheers.

niedz., 17 lip 2022, 09:31 użytkownik Sangho-Jeon ***@***.***>
napisał:

**Comment by plaskowski** [comment]
Hi @sangho-jeon,
I was able to run the project ("Run Plugin" run configuration) without an issue.
My setup: macOS Monterey 12.4, IntelliJ IDEA 2021.2.3 (Ultimate Edition), project SDK is Azul-15

Please provide a screen recording what are you doing exactly and how the problem shows up.
Another thing - try run `./gradlew runIde` from Terminal to make sure it is not IDE configuration problem.

**Comment by sangho-jeon** [comment]
i solved this problem! i think it was gradle version issue. thanks for replying.
