### ISSUE TITLE
Incompatible with 2023.1

### ISSUE THREAD

**Issue by rickythefox** [plaskowski/EmbeddedBrowserIntellijPlugin#52]
Please update to be compatible with 2023.1 IDE versions. Probably just push the version in gradle.properties?

**Comment by plaskowski** [comment]
Hi Ricky, 
will do today/tomorrow, keep fingers crossed that the build workflow (Github action) will eventually work.

**Comment by plaskowski** [comment]
Done. Released as 1.4.
