### ISSUE TITLE
Please update to IDE v232

### ISSUE THREAD

**Issue by rickythefox** [plaskowski/EmbeddedBrowserIntellijPlugin#56]
E.g. latest Webstorm is `Build #WS-232.9921.42, built on September 12, 2023`

**Comment by plaskowski** [comment]
Hi Ricky,
I was about to release the bump but I run into publish plugin problem.
So fingers crossed I will get any help soon: https://youtrack.jetbrains.com/issue/MP-5955

**Comment by plaskowski** [comment]
@rickythefox 
JB has helped so the new version will land in the store in 1-2 days.
